set_property PACKAGE_PIN W5 [get_ports i_clk]
set_property IOSTANDARD LVCMOS33 [get_ports i_clk]

set_property IOSTANDARD LVCMOS33 [get_ports {o_pdata[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_pdata[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_pdata[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_pdata[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_pdata[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_pdata[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_pdata[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_pdata[0]}]
set_property PACKAGE_PIN V14 [get_ports {o_pdata[7]}]
set_property PACKAGE_PIN U14 [get_ports {o_pdata[6]}]
set_property PACKAGE_PIN U15 [get_ports {o_pdata[5]}]
set_property PACKAGE_PIN W18 [get_ports {o_pdata[4]}]
set_property PACKAGE_PIN V19 [get_ports {o_pdata[3]}]
set_property PACKAGE_PIN U19 [get_ports {o_pdata[2]}]
set_property PACKAGE_PIN E19 [get_ports {o_pdata[1]}]
set_property PACKAGE_PIN U16 [get_ports {o_pdata[0]}]

set_property PACKAGE_PIN U18 [get_ports i_rst]
set_property IOSTANDARD LVCMOS33 [get_ports i_rst]

set_property PACKAGE_PIN L1 [get_ports o_busy]
set_property IOSTANDARD LVCMOS33 [get_ports o_busy]

set_property PACKAGE_PIN B18 [get_ports i_sdata]
set_property PACKAGE_PIN A18 [get_ports o_sdata]
set_property IOSTANDARD LVCMOS33 [get_ports i_sdata]
set_property IOSTANDARD LVCMOS33 [get_ports o_sdata]
